### PR TITLE
Add auth support

### PR DESCRIPTION
**Pull request by drakmail**
IDK how to implemet test better in current tests setup, but I'm checked manually authentication (only case without username) and it's worked

### CODE REVIEW

**Comment by gokomer** [comment]
@patrickpissurno We need authentication. Is this PR ok or should we implement another one?

**Comment by patrickpissurno** [comment]
It got outdated, so we would need a new one

**Comment by gokomer** [comment]
@drakmail are you willing to work on refactor or should I start work on it?

**Comment by patrickpissurno** [comment]
By the way, if someone can fix the conflicts this one has and get the build to pass, we could still reuse this one

**Comment by patrickpissurno** [comment]
Closed in favor of #16

**Pull request closed without merging**
