### PR TITLE
update: compiles and tests clean with V 0.2.2 e32c65c

### PR DESCRIPTION
**Pull request by JalonSolov**
Update the code to compile clean with the latest V commit as of 7/7/2021 @ 18:24 Eastern US time.

Test output:
```
---- Testing... ----------------------------------------------------------------------------------------------------------------------------------------------------------------------
 OK     422.129 ms vredis_test.v
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Summary for all V _test.v files: 1 passed, 1 total. Runtime: 422 ms.
```

### CODE REVIEW

**Comment by patrickpissurno** [comment]
Thank you!

**Comment by patrickpissurno** [comment]
Sorry to bother you with this, but I'm trying to get it to build and pass the tests via GitHub Actions, but I think I'm messing up somewhere. Would you mind taking a look at it? Just so we can remove the failing badge and tell people that it now works.

Thanks!

**Comment by JalonSolov** [comment]
Not sure... I haven't done much with github actions, but from what I just read, you may want to change the
```
v-version: latest
```
to
```
v-version: master
```
That _should_ cause it to pull the very latest version from master, instead of maybe the "latest" zip archive (which is only built on Mondays).

**Comment by spytheman** [comment]
https://github.com/patrickpissurno/vredis/pull/7 fixes the CI.

**Pull request merged**
